In [1]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.2f}'.format})


# Adjaceny matrix

In [2]:
#       A B C D   E    F   G   H   I   J K 
mat = [[0,0,0,0.5,   0,  0,  0,  0,  0,0,0],  #A
       [0,0,1,0.5,0.33,0.5,0.5,0.5,0.5,0,0],  #B
       [0,1,0,  0,   0,  0,  0,  0,  0,0,0],  #C
       [0,0,0,  0,0.33,  0,  0,  0,  0,0,0],  #D
       [0,0,0,  0,   0,0.5,0.5,0.5,0.5,1,1],  #E
       [0,0,0,  0,0.33,  0,  0,  0,  0,0,0],  #F
       [0,0,0,  0,   0,  0,  0,  0,  0,0,0],  #G
       [0,0,0,  0,   0,  0,  0,  0,  0,0,0],  #H
       [0,0,0,  0,   0,  0,  0,  0,  0,0,0],  #I
       [0,0,0,  0,   0,  0,  0,  0,  0,0,0],  #J
       [0,0,0,  0,   0,  0,  0,  0,  0,0,0]]  #K

mat = np.array(mat)
print(mat)

[[ 0.00  0.00  0.00  0.50  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  1.00  0.50  0.33  0.50  0.50  0.50  0.50  0.00  0.00]
 [ 0.00  1.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.33  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.50  0.50  0.50  0.50  1.00  1.00]
 [ 0.00  0.00  0.00  0.00  0.33  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]]


# Assuming self loop at A

If we do not assume something at A, then there is an issue with the rank of the matrix. So, we would have the eigenvalue 0 and the eigenvector [1, 0, 0, 0, ...]

In [3]:
self_loop_mat = np.copy(mat)
self_loop_mat[0][0] = 1
print(self_loop_mat)

[[ 1.00  0.00  0.00  0.50  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  1.00  0.50  0.33  0.50  0.50  0.50  0.50  0.00  0.00]
 [ 0.00  1.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.33  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.50  0.50  0.50  0.50  1.00  1.00]
 [ 0.00  0.00  0.00  0.00  0.33  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]]


### Steady state

In [4]:
eigval, eigvec = np.linalg.eig(self_loop_mat)

In [5]:
steady_states = eigvec[:, np.where(eigval==1)[0]]
steady_states /= np.sum(steady_states, axis=0)
print(steady_states)

[[ 1.00  0.00]
 [ 0.00  0.50]
 [ 0.00  0.50]
 [ 0.00  0.00]
 [ 0.00  0.00]
 [ 0.00  0.00]
 [ 0.00  0.00]
 [ 0.00  0.00]
 [ 0.00  0.00]
 [ 0.00  0.00]
 [ 0.00  0.00]]


### Steady state progression

Notice that the B->C and C->B becomes a cycle of period 2 at steady state 

In [6]:
start = np.ones(len(mat)).transpose()/len(mat)

def progression(i):
    print("{:2d}".format(i), np.matmul(np.linalg.matrix_power(self_loop_mat, i), start))

print(("{:6s}"*12).format("prog", *list(map(chr, range(97, 123)))))
for i in range(1, 6):
    progression(2**i)
    progression(2**i+1)

prog  a     b     c     d     e     f     g     h     i     j     k     
 2 [ 0.15  0.24  0.35  0.12  0.02  0.12  0.00  0.00  0.00  0.00  0.00]
 3 [ 0.21  0.47  0.24  0.00  0.06  0.00  0.00  0.00  0.00  0.00  0.00]
 4 [ 0.21  0.27  0.47  0.02  0.00  0.02  0.00  0.00  0.00  0.00  0.00]
 5 [ 0.22  0.49  0.27  0.00  0.01  0.00  0.00  0.00  0.00  0.00  0.00]
 8 [ 0.23  0.27  0.50  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 9 [ 0.23  0.50  0.27  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
16 [ 0.23  0.27  0.50  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
17 [ 0.23  0.50  0.27  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
32 [ 0.23  0.27  0.50  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
33 [ 0.23  0.50  0.27  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]


# Assuming random jump at A

If we do not assume something at A, then there is an issue with the rank of the matrix. So, we would have the eigenvalue 0 and the eigenvector [1, 0, 0, 0, ...]

In [7]:
random_jump_mat = np.copy(mat)
random_jump_mat[:, 0] = 1/len(mat)
print(random_jump_mat)

[[ 0.09  0.00  0.00  0.50  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  1.00  0.50  0.33  0.50  0.50  0.50  0.50  0.00  0.00]
 [ 0.09  1.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  0.00  0.00  0.33  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  0.00  0.00  0.00  0.50  0.50  0.50  0.50  1.00  1.00]
 [ 0.09  0.00  0.00  0.00  0.33  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
 [ 0.09  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]]


### Steady state

In [8]:
eigval, eigvec = np.linalg.eig(random_jump_mat)

In [9]:
steady_states = np.real(eigvec[:, np.where(np.isclose(eigval,1))[0]])
steady_states /= np.sum(steady_states, axis=0)
print(steady_states)

[[ 0.00]
 [ 0.50]
 [ 0.50]
 [ 0.00]
 [ 0.00]
 [ 0.00]
 [ 0.00]
 [ 0.00]
 [ 0.00]
 [ 0.00]
 [ 0.00]]


### Steady state progression

Notice that the B->C and C->B becomes a cycle of period 2 at steady state. Also not that the value at A is now 0. 

In [10]:
start = np.ones(len(mat)).transpose()/len(mat)

def progression(i):
    print("{:2d}".format(i), np.matmul(np.linalg.matrix_power(random_jump_mat, i), start))

print(("{:6s}"*12).format("prog", *list(map(chr, range(97, 123)))))
for i in range(1, 6):
    progression(2**i)
    progression(2**i+1)

prog  a     b     c     d     e     f     g     h     i     j     k     
 2 [ 0.02  0.28  0.36  0.13  0.05  0.13  0.00  0.00  0.00  0.00  0.00]
 3 [ 0.07  0.52  0.28  0.02  0.08  0.02  0.00  0.00  0.00  0.00  0.00]
 4 [ 0.02  0.34  0.52  0.03  0.02  0.03  0.01  0.01  0.01  0.01  0.01]
 5 [ 0.02  0.57  0.34  0.01  0.04  0.01  0.00  0.00  0.00  0.00  0.00]
 8 [ 0.00  0.37  0.60  0.01  0.00  0.01  0.00  0.00  0.00  0.00  0.00]
 9 [ 0.00  0.61  0.37  0.00  0.01  0.00  0.00  0.00  0.00  0.00  0.00]
16 [ 0.00  0.38  0.61  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
17 [ 0.00  0.61  0.38  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
32 [ 0.00  0.38  0.61  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
33 [ 0.00  0.61  0.38  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
